### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Manhem** [RobTillaart/TCA9555#1]
Library
https://github.com/NorthernWidget-Skunkworks/TCA9555

Datasheet
https://www.ti.com/lit/ds/symlink/tca9555.pdf

I use Port 0 as input and that seems to work (have not tried this as output). 
Port 1 is an output port in my case and this is not working. (not tried as input)

What I can find out they are sending 16 bit to the chip at the same time.
Do the chip handle that?
Don't know that the specification say.
Maybe need to to it in two 8 bit sendings.
I'm not an expert in this by I would like to learn.

Do you have any cource on how to write a library for I2C?
I would like yo do this my self.
How do you start and what shall I think about?

**Comment by RobTillaart** [comment]
quick look at the library .h file and I assume you need to set for every bit if it is an INPUT or OUTPUT

**Comment by Manhem** [comment]
That I have tried.
I have taken one pin and set it to input or output.
Input port 0, pin 0-7 is working, output port 1 pin 0-7 not.

**Comment by RobTillaart** [comment]
> Do you have any cource on how to write a library for I2C?

do you mean course or source?

Developing libraries is not trivial, ok it depends on the device. I would say one needs several years of writing code and preferably a computer science education. This helps to understand (1) how to read a datasheet, (2) how to define an interface that hides the complexity and (3) how to implement the code, and (4) how to document the library and (5) how to maintain it.

[3] can be difficult for embedded systems as there may be strict memory and performance constraints, and or a need to interact with low level timers, registers etc. 

----

OK, 
You can have a look at the develop branch - https://github.com/RobTillaart/TCA9555/tree/develop
There I have my initial commit.

Most I2C libraries I make have a similar structure 

First three functions to connect to the device.
- Constructor(address, Wire)
- begin()  + begin(sda, scl)
- isConnected()


And the lowest level like:
- readRegister()
- writeRegister()

The level in between can be seen as a technical counterpart of the business logic in a three tier architecture.

That is how it should be in theory...

_In theory there is no difference between theory and practice but in practice there is..._

**Comment by RobTillaart** [comment]
> That I have tried.
> I have taken one pin and set it to input or output.
> Input port 0, pin 0-7 is working as input, output port 1 pin 0-7 is not.

I cannot verify that, show your code.

These kind of questions are better served on the Arduino Forum imho.

**Comment by RobTillaart** [comment]
Have a look at the develop branch - https://github.com/RobTillaart/TCA9555/tree/develop
There I have a second commit

**Comment by Manhem** [comment]
Thanks for you answer.
I shall try some more places to ask if anybody knows something.

**Comment by Manhem** [comment]
Hi again.
I missed your code.
I shall try it and see how it works.

**Comment by RobTillaart** [comment]
@Manhem 
> I shall try it and see how it works.

Please do as I have no hardware to test.

I will add a 16 bit interface (which will be two 8 bit calls) if needed.

**Comment by Manhem** [comment]
Hi.
I have now done some small tests with the hardware I have and so far it works perfectly.
More tests is comming.
I let you know if I find any problem.
Thanks a lot for you help.

**Comment by RobTillaart** [comment]
> so far it works perfectly.

I made a first release so other people may enjoy / test it too.

**Comment by RobTillaart** [comment]
@Manhem 
Merged 16 bit interface.  ==> 0.1.1

----

The flow of library development is (simplified)
1. read the datasheet first until you understand what the device can do.
2. make a draft of the interface you want to offer
3. choose a minimalistic subset that is easiest to implement. 
4. write code until you have that minimal version working. 
5. write examples to test the library
6. write unit tests if possible 
7. Test, or let someone else test
8. add more functions if behaves stable
9. go to step 5

Steps I made for this library
- I2C connection, constructor etc
- low level register read / write  (raw low level  access)
- 8 pins interface
- 1 pin interface
- 16 pin interface

Important to remember
- First get it working (freeze that version as it is the functional reference) 
- and only if it is a problem start optimizing for memory / performance

**Comment by RobTillaart** [comment]
Library is stable so I close the issue.
If needed reopen it or create a new issue
