### ISSUE TITLE
Just a small question

### ISSUE THREAD

**Issue by Manhem** [RobTillaart/TCA9555#17]
Hi.
Do you have any function in the library to see if the I2C bus is busy?
And if so, how do I use it???

**Comment by RobTillaart** [comment]
interesting question.

As far as I know no such function exists.

In a single tasking environment a collision of I2C transactions cannot happen unless you try to put I2C commands in an interrupt.

In a multitasking/threading environment you must put semaphores around shared resources like an I2C bus. 
This guards that only one thread can access the resource at a time.
However, just a semaphore is not enough as your code should also prevent starvation. This is the scenario in which three threads want access to a resource and two of them have alternating access, effectively blocking the 3rd thread.
Then there is deadlock, e,g, two threads want access to two resources to do a task, thread one gets resource A and thread two get resource B. They effectively block each other. 

There are more problems with shared resources possible, and thankfully solutions exist, please note these are not trivial.
This is "hard core" computer science and if you want to learn more about this you could read a book about the internals of an OS e.g. Linux to see how this is done in practice.

A reasonable fool proof detection can be made if you put a transaction flag around every I2C transfer, both your own code and in the used libraries. This flag must be guarded with a semaphore as it represents the shared resource.
If a thread wants to do I2C it sets the transaction to true and all other threads will see I2C is busy and they should wait. 
If a thread is done it sets the transaction to false and other threads can claim it for their communication.
A more elaborated version might use an integer as flag, so the thread can put its thread-ID into the transaction flag, so other threads can see which process/thread is using I2C.

**Comment by RobTillaart** [comment]
@Manhem 
If this answers your question, please close the issue.

**Comment by Manhem** [comment]
Thanks for your good answer.
I think I need to read more about this and see what I can do.

But your answer to my question is that your library don't have this function inside. 

Maybe in the future you can also put in this function to your libraries?

Thanks for your help.

**Comment by RobTillaart** [comment]
> Maybe in the future you can also put in this function to your libraries?

No, the right place for such functionality should be as part of the I2C library (which is board specific).
