### ISSUE TITLE
no pinMode() in TCA95x5_digitalWrite.ino

### ISSUE THREAD

**Issue by nerdyscout** [RobTillaart/TCA9555#18]
Hey @RobTillaart 
thank you for this lib, it just helped me a lot getting started. But it gave me also a hard time running as I tried to output data but seems like there is no pinMode() in the digitalWrite examples. Is this really correct?

**Comment by RobTillaart** [comment]
>  Is this really correct?

No it is not, sorry. 
The examples were written long ago (2021) with no hardware nearby to do the ultimate example test.

I will update the examples a.s.a.p. (and check if there are other minor things to fix I can include).

**Comment by RobTillaart** [comment]
@nerdyscout 

Created a develop branch (prep version 0.3.2) in which the examples are updated.
If you have time could you verify if they work as intended?  
and of course if your code still works?

**Comment by nerdyscout** [comment]
my personal code wont be effected as I have to rewrite everything on another platform.
But I can confirm TCA9555_digitalWrite.ino works now how I suspect it. 
thank you for your quick reply!
