### ISSUE TITLE
TCA9535 is inaccesible

### ISSUE THREAD

**Issue by mcenderdragon** [RobTillaart/TCA9555#7]
hi o/
it seems like the header isw missing the public: declration for the 35 constructor.

**Comment by RobTillaart** [comment]
Thanks for filing this issue,
I will fix it later this week (might be today), 

Todo:
- add unit test for derived class
- add example for derived class

**Comment by RobTillaart** [comment]
@mcenderdragon 
Created a PR to fix this issue - build may fail as there are problems with build-CI at the moment.

**Comment by RobTillaart** [comment]
Merged PR into master,
Thanks again for reporting!
